/*
 * Public API Surface of @xtein/sdk
 */


/*
 * SDK placeholder generated by Angular.
 */
export * from './lib/sdk';


/*
 * ================================================================
 * APPLICATION
 * ================================================================
 */

export * from './lib/contracts/application/application-request';
export * from './lib/contracts/application/application-descriptor';
export * from './lib/contracts/application/application-error';

/*
 * ================================================================
 * NAVIGATION
 * ================================================================
 */

export * from './lib/contracts/navigation/application-tree-node';

/*
 * ================================================================
 * REMOTE / MICROFRONTEND
 * ================================================================
 */

export * from './lib/contracts/remote/remote-descriptor';

/*
 * ================================================================
 * WORKSPACE
 * ================================================================
 */

export * from './lib/contracts/workspace/workspace-tab';

/*
 * ================================================================
 * TOOLBAR
 * ================================================================
 */

export * from './lib/contracts/toolbar/toolbar-action';
export * from './lib/contracts/toolbar/toolbar-command';
export * from './lib/contracts/toolbar/toolbar-state';
export * from './lib/contracts/toolbar/record-toolbar-mode';
export * from './lib/contracts/toolbar/record-toolbar-permissions';
export * from './lib/contracts/toolbar/record-toolbar-capabilities';
export * from './lib/contracts/toolbar/record-toolbar-state';

/*
 * ================================================================
 * TOOLBAR HELPERS
 * ================================================================
 */

export * from './lib/toolbar/toolbar-state.builder';