export const environment = {
  production: true,
  apiUrlNode: '/e',
  apinet: '/api',
  apiDocElec: 'http://190.85.54.78:8770',
  //apiBaseUrl: 'https://api.prod.colchonessunmoon.com/api',
  apiBaseUrl: "/api",
  apiWebSocket: 'wss://api.prod.colchonessunmoon.com/ws/',
  correo_compra: 'abastecimiento@artdecon.com',
  URL_XTEIN: 'https://xteinweb.colchonessunmoon.com/home',
  reportes: 'https://reportes.colchonessunmoon.com',
  files: 'https://reportes.colchonessunmoon.com',
  dashboard: 'https://dashboard.colchonessunmoon.com',
  dashboardDesigner: '/api/dashboard-designer',
  userDiseno: 'administratos',
  passUserDiseno: '2022.Admin',
  apiDiseno: 'https://apidiseno.colchonessunmoon.com/files?command=GetDirContents&arguments=',
  apiArchivos: 'http://181.79.25.235:8556',
  webhookNotifyUrl: 'https://agentes.colchonessunmoon.com/webhook/ac110ada-c289-424d-8660-3b67d0e02f33',
};