import type { XteinChartOptions, XteinPieChartOptions, XteinBarGaugeOptions, XteinSchedulerOptions } from '@xtein/ui';
import { TableroControlsContext } from '../models/tablero-controls.model';
export function createTableroControlOptions(context: TableroControlsContext) {
    const pieChartOptions1: XteinPieChartOptions = { resolveLabelOverlapping: "shift", type: "doughnut", animation: true, innerRadius: 0.7, legend: { horizontalAlignment: "right", verticalAlignment: "bottom", margin: 0, visible: true, paddingTopBottom: 2, rowItemSpacing: 2, markerSize: 10 }, series: [{ argumentField: "region", label: { backgroundColor: "none", format: "fixedPoint", visible: false, customizeText: context.customizeLabel, connector: { visible: false, width: 0.5 } }, smallValuesGrouping: { mode: "smallValueThreshold", threshold: 4.5 } }] };
    const chartOptions1: XteinChartOptions = { legend: { visible: false }, argumentAxis: { visible: false, tickInterval: 1, tick: { visible: false } }, commonAnnotationSettings: { type: "custom", series: "Population", allowDragging: true }, series: [{ type: "bar", name: "Population", argumentField: "name", valueField: "population", color: "#2EADE5" }], valueAxis: [{ visible: false, valueMarginsEnabled: false, grid: { visible: false }, label: { visible: false }, tick: { visible: false } }], annotations: [{ color: "#fff", data: context.populationData[2], argument: context.populationData[2].name, border: { color: "rgba(10,57,96,.25)", dashStyle: "solid", width: 1 } }] };
    const barGaugeOptions1: XteinBarGaugeOptions = { backgroundColor: "rgba(18,94,220,.075)", startValue: 0, redrawOnResize: true, endValue: 100, values: [67.27], relativeInnerRadius: 0.6, geometry: { startAngle: 180, endAngle: 360 }, legend: { visible: false }, label: { connectorColor: "rgba(10,57,96,.75)", indent: 0, visible: true, font: { color: "transparent", opacity: 0 }, format: { type: "fixedPoint", precision: 1 } }, animation: { easing: "easeOutCubic", duration: 500 } };
    const schedulerOptions1: XteinSchedulerOptions = { timeZone: "America/Bogota", currentView: "agenda", views: ['agenda'], currentDate: context.currentDate, firstDayOfWeek: 1, startDayHour: 6, showAllDayPanel: false, editing: true, resources: [{ fieldExpr: "assigneeId", label: "Responsable", allowMultiple: true, dataSource: context.assignees, useColorAsDefault: true }, { fieldExpr: "priorityId", label: "Prioridad", dataSource: context.priorities }] };
    const dottedGrid = { dashStyle: "dot", color: "rgba(10,57,96,.075)", visible: true, width: 3 };
    const chartOptions2: XteinChartOptions = { legend: { visible: false }, margin: { top: 6 }, argumentAxis: { discreteAxisDivisionMode: "crossLabels", color: "rgba(10,57,96,.05)", visible: false, tickInterval: 10, tick: { visible: false }, grid: dottedGrid }, valueAxis: [{ visible: false, valueMarginsEnabled: false, grid: { color: "rgba(10,57,96,.05)", visible: false }, label: { visible: false }, tick: { visible: false } }], series: [{ type: "line", name: "Population", argumentField: "name", valueField: "population", color: "#2EADE5", width: 5, point: { size: 16 }, hoverStyle: { width: 6 } }] };
    return { pieChartOptions1, chartOptions1, barGaugeOptions1, schedulerOptions1, chartOptions2 };
}
