/**
 * Describes one filter field returned by the shared XTEIN
 * filter metadata endpoint.
 *
 * Backend property names are intentionally preserved because
 * they are part of the existing XTEIN contract.
 */
export interface XteinRecordFilterField {

  /**
   * Existing filter item/order identifier.
   */
  ITEM?:
    number |
    string;


  /**
   * User-facing field title.
   */
  TITULO:
    string;


  /**
   * Backend field name.
   */
  CAMPO:
    string;


  /**
   * Existing XTEIN field type.
   *
   * Examples:
   *
   * - texto
   * - smalldatetime
   * - bit
   * - lista
   * - listauni
   * - searchbox
   */
  DATA_TYPE:
    string;


  /**
   * Additional field configuration.
   *
   * Its structure depends on DATA_TYPE.
   */
  DATA?:
    unknown;


  /**
   * Backend table associated with the field.
   */
  TABLA?:
    string;


  /**
   * Current filter value.
   */
  VALOR?:
    unknown;
}


/**
 * Represents one criterion sent to an application query.
 *
 * This is equivalent to one entry of the existing ESTRUCTURA
 * generated by the shared XTEIN filter.
 */
export interface XteinRecordFilterCriterion {

  /**
   * Backend field name.
   */
  CAMPO:
    string;


  /**
   * Filter expression for the field.
   */
  EXPRESION:
    string;


  /**
   * Backend table associated with the field.
   */
  TABLA:
    string;
}


/**
 * Result produced by the shared record filter.
 *
 * The application remains responsible for executing
 * its own query.
 */
export interface XteinRecordFilterResult {

  /**
   * Existing textual filter expression.
   *
   * This value is preserved because some applications
   * and report operations still use QFILTRO.
   */
  FILTRO:
    string;


  /**
   * Structured filter criteria sent to the application.
   */
  ESTRUCTURA:
    XteinRecordFilterCriterion[];
}


/**
 * Represents one item returned by a shared lookup endpoint.
 */
export interface XteinRecordFilterLookupItem {

  /**
   * Lookup fields are dynamic because the existing backend
   * returns different columns depending on the configured query.
   */
  [key: string]:
    unknown;
}


/**
 * Represents one paged result used by remote filter lists.
 */
export interface XteinRecordFilterLookupPage {

  /**
   * Current page items.
   */
  items:
    XteinRecordFilterLookupItem[];


  /**
   * Total available items.
   */
  totalCount:
    number;
}